// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nevrhapuzjabklfumxzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ldnJoYXB1emphYmtsZnVteHpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNjQ3MDcsImV4cCI6MjA2Nzc0MDcwN30._gfj0X_Wtpzj9Z0FoG4Wci_r6yHzte1NvfypMSVBn9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});